- name: Build and test with Maven and Sonar
        run: |
          mvn -B verify sonar:sonar \
          -DskipTests \
          -Dsonar.projectKey=Akissi14_Tp_Docker \
          -Dsonar.organization=akissi14 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          --file backend/pom.xml